### PR TITLE
Numpy 1.14 results from bambi

### PR DESCRIPTION
**Pull request by pllim**
Numpy 1.14 results from `bambi`; also renamed older `bambi` results. 🦌

### CODE REVIEW

**Comment by pllim** [comment]
p.s. I don't understand why the `diff` has no deletions... Technically, renamed benchmarks should have some deletions... 🤔 I hope I didn't mess up anything again. 😱

**Comment by pllim** [comment]
p.p.s. This is the generated page from my `results` branch. Does this look right? https://pllim.github.io/astropy-benchmarks/#/

**Comment by astrofrog** [comment]
@pllim - I already renamed all the old files in the results branch :)

**Comment by astrofrog** [comment]
This looks good! Once asv is fixed in terms of how skip-existing behaves, it would be good if you re-run asv with ``--skip-existing-successful`` and all Numpy configurations to fill in the gaps.

**Comment by astrofrog** [comment]
By gaps I mean the fact that the bambi results don't cover all commits for a particular version of Numpy:

screen shot 2018-01-16 at 19 20 46

**Comment by pllim** [comment]
@astrofrog , sounds like a plan. Thanks!

**Pull request merged**
