### PR TITLE
start of modeling benchmarks

### PR DESCRIPTION
**Pull request by nden**
I intend to add some more benchmarks but am pushing this branch to find out if this looks correct.
Any feedback appreciated - @astrofrog @pllim

### CODE REVIEW

**Comment by pllim** [comment]
I never wrote one before, I just run them. Therefore, I'll defer to @astrofrog on this one.

**Comment by astrofrog** [comment]
@nden - there is a failure related to these new benchmarks on Travis:

```
      Traceback (most recent call last):
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 795, in <module>
                 commands[mode](args)
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 740, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 725, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 711, in disc_benchmarks
                 for benchmark in disc_objects(module):
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 682, in disc_objects
                 for benchmark in disc_class(val):
               File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 661, in disc_class
                 for key, val in inspect.getmembers(klass):
               File "/home/travis/build/astropy/astropy-benchmarks/env/7d78ea8ae119b796a0d35777fbc5b651/lib/python3.6/inspect.py", line 342, in getmembers
                 value = getattr(object, key)
               File "/home/travis/build/astropy/astropy-benchmarks/env/7d78ea8ae119b796a0d35777fbc5b651/lib/python3.6/site-packages/astropy/modeling/core.py", line 178, in n_inputs
                 return len(cls.inputs)
             TypeError: object of type 'property' has no len()
```

Do you have any idea what this could be due to?

**Comment by astrofrog** [comment]
I think somehow it might be trying to collect tests on the model classes

**Comment by nden** [comment]
@astrofrog I don't see the astropy version used in the benchmarks (I'm probably just missing it somehow). I've seen a similar error with units in compound models but it has been fixed since then.

The examples in this PR pass locally.

**Comment by astrofrog** [comment]
I'll investigate, but I will need to delay it to the week after next (I am on vacation next week).

**Comment by nden** [comment]
Thanks! No problem, I don't have time to work on this now too.

**Comment by nden** [comment]
Superseded by #51 .

**Pull request closed without merging**
