### PR TITLE
Fix mem profiling error for ASCII Table

### LINKED ISSUE #87: Some table memory benchmarks failing
I haven't had a chance to investigate yet:

```
[ 19.68%] ··· io_ascii.table.TableSuite.mem_table_init                                                                                                   failed
[ 19.68%] ···· Traceback (most recent call last):
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 729, in run
                   sizeof2 = asizeof.asizeof([obj, obj])
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2708, in asizeof
                   s = _asizer.asizeof(*t)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in asizeof
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 [Previous line repeated 1 more time]
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2050, in _sizer
                   infer=self._infer_)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1711, in _typedef
                   v.set(**_numpy_kwds(obj))
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1269, in set
                   self.reset(**d)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1278, in reset
                   raise ValueError('invalid option: %s=%r' % ('base', base))
               ValueError: invalid option: base=-7880

[ 19.84%] ··· io_ascii.table.TableSuite.mem_table_outputter                                                                                              failed
[ 19.84%] ···· Traceback (most recent call last):
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 729, in run
                   sizeof2 = asizeof.asizeof([obj, obj])
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2708, in asizeof
                   s = _asizer.asizeof(*t)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in asizeof
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 [Previous line repeated 1 more time]
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2050, in _sizer
                   infer=self._infer_)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1711, in _typedef
                   v.set(**_numpy_kwds(obj))
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1269, in set
                   self.reset(**d)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1278, in reset
                   raise ValueError('invalid option: %s=%r' % ('base', base))
               ValueError: invalid option: base=-7880
```

### PR DESCRIPTION
**Pull request by pllim**
Fix #87 

Many thanks to @pv for the help!

Bonus: PEP 8

cc @mhvk (somehow unable to add you as reviewer)

### CODE REVIEW

**Comment by mhvk** [comment]
Nice sleuthing to understand the problem, but I do worry this now tests something else than intended... So, better to have whoever designed the benchmark have a look...

**Comment by pllim** [comment]
Git blames it to @mdmueller , who added the benchmarks 5 years ago. 🤷‍♀

**Comment by pllim** [comment]
I don't understand the test error:
```
asv: error: unrecognized arguments: --strict
```

**Comment by astrofrog** [comment]
I think it must be that asv is too old on some configs

**Comment by bsipocz** [comment]
Unrelated to this PR, but I noticed here that the travis testing runs forever. Should we indeed run such thorough testing, or maybe just do one or two of the import benchmarks would do the trick?

**Comment by pllim** [comment]
I don't see any error in the log but it still failed. Any more ideas?

**Comment by astrofrog** [comment]
As @mhvk said, it could be that with these changes we aren't testing the original intent of this test - since @mdmueller may not be able to review this, I'll tag @taldcroft for input.

**Comment by astrofrog** [comment]
@bsipocz 

> Unrelated to this PR, but I noticed here that the travis testing runs forever. Should we indeed run such thorough testing, or maybe just do one or two of the import benchmarks would do the trick?

The builds take 3-6 minutes each which doesn't seem too long especially since this repo is pretty low activity. I think it's important we test all the benchmarks since otherwise they will silently fail on the benchmark machine. Note that we run the benchmarks in quick mode here, which means we only run them once each, not multiple times to get an average as they do on the real machine.

**Comment by bsipocz** [comment]
> The builds take 3-6 minutes each

it's more like 20+mins, thus I was asking

**Comment by astrofrog** [comment]
Yeah something is wrong... it was 3-6 a week ago

**Comment by taldcroft** [comment]
If the `mem_table_init` is just about finding the memory size of the table, then doing that `as_array` should be fine.

**Comment by pllim** [comment]
I reverted my change to `.travis.yml` as fixing it is out of scope.

**Pull request merged**
