### PR TITLE
Add some quantity initialization and computation benchmarks.

### PR DESCRIPTION
**Pull request by mhvk**
Adds some benchmarks, also slightly rewrites others, to ensure we are timing `Quantity`, not numpy.

### CODE REVIEW

**Comment by astrofrog** [comment]
@mhvk - I fixed Travis, can you rebase?

**Comment by astrofrog** [comment]
Note to self: I will need to delete past results for the benchmarks that are being changed here before re-running.

**Comment by mhvk** [comment]
@astrofrog - thanks! I rebased and tests now pass.

**Comment by astrofrog** [comment]
@mhvk - the latest results are online: http://astropy.github.io/astropy-benchmarks - the results you should look at are the ones for the machine 'ant'. Let me know if you spot any issues!

**Comment by mhvk** [comment]
@astrofrog - thanks! For quantity, it looks good except that views have become slightly more expensive but since this solved quite a few small bugs, and it still is fast I think it is OK.

**Pull request merged**
