### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by nden** [comment]
Thanks!

**Comment by nden** [comment]
Apparently it expects someone else to do a review.

**Comment by larrybradley** [comment]
Thanks, @nden!  Apparently you don't have write access (neither do I) -- "At least 1 approving review is required by reviewers with *write* access."

**Comment by larrybradley** [comment]
CC:  @pllim ?

**Comment by pllim** [comment]
I want to consult @astrofrog on how this name change is going to affect the cron stuff that he set up. Last time names were changed, some manual JSON tweaking was necessary, if I remember correctly.

**Comment by astrofrog** [comment]
Yes this requires also fixing all the files in the results branch. Could one of you open a PR to do that? (just search and replace the change)

**Comment by astrofrog** [comment]
(I'll then merge both PRs at the same time to avoid issues)

**Comment by astrofrog** [comment]
Fixed the results files in https://github.com/astropy/astropy-benchmarks/commit/b66486f61029882146f993d13cab753d564a1dfb

**Pull request merged**
