### PR TITLE
Rename benchmarks to mirror astropy core package structure

### PR DESCRIPTION
**Pull request by astrofrog**
This renames the benchmarks. I'll rename the results in a separate PR.

### CODE REVIEW

**Comment by pllim** [comment]
LGTM but @bsipocz should have a look too. Thanks!

**Comment by bsipocz** [comment]
All looks good to me, thanks @astrofrog for picking this up.

**Comment by astrofrog** [comment]
Ok, I'll merge this now. @pllim - see https://github.com/astropy/astropy-benchmarks/pull/33 if you need a script to rename results files.

**Comment by pllim** [comment]
Should we remove the `rename` branch?

**Pull request merged**
