### PR TITLE
Add benchmarks for attaching differentials to representations

### PR DESCRIPTION
**Pull request by adrn**
This is a complement to astropy/astropy#7924 that adds benchmarks relevant to the speed improvements in that PR.

### CODE REVIEW

**Comment by adrn** [comment]
Any idea what's up with that travis test?

**Comment by pllim** [comment]
My attempt to fix this is at astropy/astropy#7932 . For now, you need `pytest` package installed.

**Comment by astrofrog** [comment]
@adrn - can you rebase this? (there is a conflict)

**Comment by eteq** [comment]
I did a rebase here for @adrn (and pushed it up) because I wanted it anyway to test some changes I'm making.

**Pull request merged**
