### PR TITLE
Added WCSAxes benchmarks

### LINKED ISSUE #28: Add WCSAxes benchmarks
WCSAxes has some performance issues in places, so we should add benchmarks. There are already a few here:

https://github.com/astrofrog/wcsaxes-benchmarks/blob/master/benchmarks/benchmarks.py

leftover from when WCSAxes was a separate package.

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes #28 

@pllim - once we merge this, this will require me to rename the existing results files to include the Matplotlib and Scipy version. I'll need to do that before we re-run asv with ``--skip-existing``.

### CODE REVIEW

**Comment by pllim** [comment]
@astrofrog , please share your magical renaming incantation so I can rename them on my fork too. Thanks!

**Comment by bsipocz** [comment]
@pllim - https://github.com/astropy/astropy-benchmarks/pull/33#issue-288096487

**Comment by pllim** [comment]
@bsipocz , I already renamed according to #33. However, I don't see any incantation there to "rename the existing results files to include the Matplotlib and Scipy version." Did I miss something?

**Comment by bsipocz** [comment]
oh, ok, sorry about the misunderstanding.

**Comment by astrofrog** [comment]
I haven't done any renaming yet, but once I do I will post my magic incantation!

**Pull request merged**
