### PR TITLE
Add sigma clipping benchmarks

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by pllim** [comment]
@larrybradley said, "The `time_3d_array` times out currently, but it will be ~10x faster." Merging.

**Comment by astrofrog** [comment]
I think it's not ideal to have it time out before the performance improvement - can we not just use a smaller array?

**Comment by larrybradley** [comment]
OK.

**Comment by pllim** [comment]
Ops. Sorry if I merged this too soon.

**Pull request merged**
